# Generated by Django 4.2.2 on 2023-06-14 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('films', '0009_alter_comment_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='photo_url',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='actor',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='movie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='films.movie'),
        ),
        migrations.AlterField(
            model_name='director',
            name='birth_year',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='director',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='director',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='movie',
            name='description',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, to='films.genre'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
